import Head from 'next/head';
import Homepage from '../components/Homepage';
import Navpage from '../components/Navpage';
import Navbar from '../components/Navbar';
import About from '../components/About';

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className=" ">
        <Navpage />
        <Navbar />
        <Homepage />
        <About/>
      </div>
    </div>
  );
}
